import { Dimensions } from "react-native";

const width = Dimensions.get("window").width;
const height = Dimensions.get("window").height;

export default {
  device: {
    width: width,
    height: height,
  },
  border: {
    radius: "12px",
  },
  fonts: {
    regular: "PublicSans_400Regular",
    medium: "PublicSans_500Medium",
    bold: "PublicSans_700Bold",
    sizes: {
      xxsmall: "10px",
      xsmall: "10px",
      small: "14px",
      medium: "18px",
      large: "24px",
      xlarge: "30px",
      xxlarge: "39px",
      xxxlarge: "64px",
    },
  },
  colors: {
    primary: "#99C5F1",
    lightBlue: "#e3ebf3",
    subtext: "#8D919E",
    white: "#FFFFFF",
    black: "#000000",
    purple: "#1f145c",
    orange: "#FF8200",
    border: "#C5CADA",
    red: "#FF0000",
    danger: "#FF4842",
    gray: "#808080",
    lightGray: "#9CA3AF",
    opacityBlack: "#575F69",
    buttonActive: "#007bff",
    darkGray: "#1F2937",
    green: "#04D361",

    blue: "#00FEFE",
    filterBackground: "#D9D9D9",
    lightGrayBox: "#3B3B3B",
    whiteGray: "#E2DBCE",
    inputColor: "#212B36",
    inputBorderColor: "#919EAB",
    placeholderTextColor: "#919EAB",
    yellow: "#FFBB56",
    facebook: "#3B5998",
    linkedin: "#0E76A8",
    apple: "#212223",
    transper: "#F4F4F4",
    smokeWhite: "#F4F4F7",
    drawerIcons: "#919EAB",
    cardHover: "rgba(0, 52, 101, 0.8)",
    cardActived: "rgba(0, 0, 0, 0.1)",
  },
  shadow: {
    shadowOpacity: 0.5,
    shadowOffset: { width: 5, height: 3 },
    shadowRadius: 2,
    elevation: 5,
    shadowColor: "#00000066",
  },
  spacings: {
    xxsmall: "6px",
    xsmall: "12px",
    small: "14px",
    medium: "16px",
    large: "18px",
    xlarge: "24px",
    xxlarge: "34px",
    xxxlarge: "42px",
  },
};
